USE [master]
GO

CREATE DATABASE [MyCompany];

GO

USE [MyCompany]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customer](
	[CustomerId] [UNIQUEIDENTIFIER] NOT NULL,
	[FirstName] [NVARCHAR](255) NULL,
	[LastName] [NVARCHAR](255) NULL,
	[Company] [NVARCHAR](255) NULL,
	[Created] [DATETIME] NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Customer] ADD  CONSTRAINT [DF_Customer_Created]  DEFAULT (GETDATE()) FOR [Created]
GO


USE [MyCompany]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Invoice](
	[InvoiceId] [UNIQUEIDENTIFIER] NOT NULL,
	[CustomerId] [UNIQUEIDENTIFIER] NOT NULL,
	[Reference] [NVARCHAR](255) NOT NULL,
	[Total] [DECIMAL](18, 2) NOT NULL,
	[Created] [DATETIME] NOT NULL,
 CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED 
(
	[InvoiceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Invoice] ADD  CONSTRAINT [DF_Invoice_Created]  DEFAULT (GETDATE()) FOR [Created]
GO


USE [MyCompany]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[InvoiceItem](
	[InvoiceItemId] [UNIQUEIDENTIFIER] NOT NULL,
	[InvoiceId] [UNIQUEIDENTIFIER] NOT NULL,
	[ItemId] [UNIQUEIDENTIFIER] NOT NULL,
	[Quantity] [INT] NOT NULL,
	[Created] [DATETIME] NOT NULL,
 CONSTRAINT [PK_InvoiceItem] PRIMARY KEY CLUSTERED 
(
	[InvoiceItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[InvoiceItem] ADD  CONSTRAINT [DF_InvoiceItem_Created]  DEFAULT (GETDATE()) FOR [Created]
GO


USE [MyCompany]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Item](
	[ItemId] [UNIQUEIDENTIFIER] NOT NULL,
	[Name] [NVARCHAR](255) NOT NULL,
	[Price] [DECIMAL](18, 2) NOT NULL,
	[Created] [DATETIME] NOT NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED 
(
	[ItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Item] ADD  CONSTRAINT [DF_Item_Created]  DEFAULT (GETDATE()) FOR [Created]
GO


